FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=jujubis
ENV N8N_BASIC_AUTH_PASSWORD=Vai1cafezin?*
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV WEBHOOK_URL=https://jujubis-la7o.onrender.com
N8N_AUTH_EXCLUDE_ENDPOINTS=healthz

EXPOSE 5678
